# Generated by Django 5.0.14 on 2026-04-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.CharField(max_length=64)),
                ('yjs_state', models.BinaryField(blank=True, null=True)),
                ('content', models.TextField(blank=True, default='')),
                ('updated_at', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'rooms',
                'ordering': ('-updated_at', '-id'),
                'managed': False,
            },
        ),
    ]
